### PR TITLE
feat: allow regex matching

### PR DESCRIPTION
**Pull request by Thomzoy**
See #93

### CODE REVIEW

**Comment by ochedru** [comment]
Thank you for your PR! Can you please rebase it? I had to revert to ubuntu-20.04 in the github actions to make the build work.

**Comment by Thomzoy** [comment]
> Thank you for your PR! Can you please rebase it? I had to revert to ubuntu-20.04 in the github actions to make the build work.

Done !

**Comment by Thomzoy** [comment]
Well I should remove type hinting for compatibility with Python 2

**Comment by ochedru** [comment]
> Well I should remove type hinting for compatibility with Python 2

Yup, and there is also an f-string. Maybe we'll drop support for Python 2 in the next major version.

**Comment by Thomzoy** [comment]
> > Well I should remove type hinting for compatibility with Python 2
> 
> Yup, and there is also an f-string. Maybe we'll drop support for Python 2 in the next major version.

Ah yes my bad, I don't have Python 2 on my system so I cannot check it thoroughly

**Comment by ochedru** [comment]
The tests are ok. Could you please add an example of regex matching in the readme file, so users know how to use your feature? Thanks!

**Comment by Thomzoy** [comment]
Done !

**Pull request merged**
