### PR TITLE
Support pip 20

### PR DESCRIPTION
**Pull request by missimer**
Pip 20 has moved some code around.  This seems to fix it.  Only tested locally.  First time contributing, welcome any feedback.

### CODE REVIEW

**Comment by ochedru** [comment]
Thank you for your PR!

**Comment by larsrinn** [comment]
When will this be released? It currently breaks our CI pipeline...

**Comment by ochedru** [comment]
The build fails with Python 3.4: https://travis-ci.org/dhatim/python-license-check/jobs/641498145

**Comment by ochedru** [comment]
Removed support for Python 3.4. Released version 0.4.0.

**Pull request merged**
